
---
- hosts: HYDRO
  become: true
  become_method: sudo

  vars:
    # Remote.
    proj_des:    '/home/odroid/RPi2/'
    sysd:        '/lib/systemd/system/'

    # Controller.
    c_home:           "{{ lookup('env','HOME') }}/"
    proj_src:         '{{c_home}}PycharmProjects/RPi2/'
    service:          '{{proj_src}}Hydro.service'


  tasks:

   # - name: Create Horizon directory
   #   file: path="{{prog_dir}}" state=directory

    - name: Copy Hydro Service
      copy: src={{service}} dest={{sysd}}

    - name: Stop Hydro service
      systemd: state=stopped name=Hydro masked=no enabled=yes

    - name: Copy Hydro Project
      synchronize: src={{proj_src}} dest={{proj_des}} dirs=yes

    - name: Chown Chgrp
      file: path=/home/odroid/ owner=odroid group=odroid recurse=yes

#    - name: Start Hydro service
#      systemd: state=started name=Hydro masked=no enabled=yes daemon_reload=yes
