
---
- hosts: HYDRO

  vars:
    # Remote.
    proj_des:    '/home/odroid/'

    # Controller.
    c_home:           "{{ lookup('env','HOME') }}/"
    proj_src:         '{{c_home}}PycharmProjects/RPi2'


  tasks:



    - name: Stop Light service
      systemd: state=stopped name=Light masked=no enable=yes

    - name: Stop Water service
      systemd: state=stopped name=Light masked=no enable=yes

    - name: Stop Sensor service
      systemd: state=stopped name=Sensor masked=no enable=yes

    - name: Copy Hydro Project
      copy: src={{proj_src}} dest={{proj_des}}

    - name: Start Light service
      systemd: state=started name=Light masked=no enable=yes

    - name: Start Water service
      systemd: state=started name=Water masked=no enable=yes

    - name: Start Sensor service
      systemd: state=started name=Sensor masked=no enable=yes
