
---
- hosts: HYDRO
  become: true
  become_method: sudo

  vars:
    # Remote.
    proj_des:    '/home/odroid/'
    sysd:        '/lib/systemd/system/'

    # Controller.
    c_home:           "{{ lookup('env','HOME') }}/"
    proj_src:         '{{c_home}}PycharmProjects/RPi2/'
    service:          '{{proj_src}}Service/Hydro.service'


  tasks:


    - name: Copy Hydro Service
      copy: src={{service}} dest={{sysd}}

    - name: Stop Hydro service
      systemd: state=stopped name=Hydro masked=no enabled=yes

    - name: Copy Hydro Project
      copy: src={{proj_src}} dest={{proj_des}} state=directory

    - name: Start Hydro service
      systemd: state=started name=Hydro masked=no enabled=yes
